from decouple import config

AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
REGION_NAME = config('REGION_NAME')
QUEUE_URL = config('QUEUE_URL')
BUCKET_NAME = config('BUCKET_NAME')
BUCKET_ARN = config('BUCKET_ARN')